# Generated by Django 4.2.4 on 2023-09-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstantsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=256, verbose_name='site name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone1', models.PositiveIntegerField(verbose_name='phone1')),
                ('phone2', models.PositiveIntegerField(verbose_name='phone2')),
                ('facebook', models.CharField(max_length=256, verbose_name='facebook')),
                ('twitter', models.CharField(max_length=256, verbose_name='twitter')),
                ('instagram', models.CharField(max_length=256, verbose_name='instagram')),
                ('linkedin', models.CharField(max_length=256, verbose_name='linkedin')),
                ('youtube', models.CharField(max_length=256, verbose_name='youtube')),
                ('vk', models.CharField(max_length=256, verbose_name='vk')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
            ],
            options={
                'verbose_name': 'Constant',
                'verbose_name_plural': 'Constants',
            },
        ),
    ]
