# Generated by Django 4.2.4 on 2023-09-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0002_constants_delete_constantsmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=512, verbose_name='description')),
                ('image', models.ImageField(upload_to='uploads/slider/', verbose_name='image')),
                ('button_title', models.CharField(max_length=64, verbose_name='button title')),
                ('button_slug', models.CharField(max_length=256, verbose_name='button slug')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
