# Generated by Django 4.2.4 on 2023-09-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0003_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='action',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='button_slug',
            field=models.CharField(blank=True, max_length=256, verbose_name='button slug'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='button_title',
            field=models.CharField(blank=True, max_length=64, verbose_name='button title'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(blank=True, max_length=512, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/slider/', verbose_name='image'),
        ),
    ]
