# Generated by Django 4.2.4 on 2023-09-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_page_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=128, verbose_name='title')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='url')),
                ('image', models.ImageField(blank=True, upload_to='uploads/blog/%Y-%m-%d/', verbose_name='image')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('meta_title', models.CharField(blank=True, max_length=128, verbose_name='m_title')),
                ('meta_keywords', models.CharField(blank=True, max_length=128, verbose_name='m_keywords')),
                ('meta_description', models.CharField(blank=True, max_length=128, verbose_name='m_description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
